In [ ]:
#Задание 1
#Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]))

In [1]:
import numpy as np

In [12]:
a = np.arange(10)
a = a[::-1]

In [13]:
a

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
#Задание 2
#Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [31]:
f'введите количество элементов'
n=int(input())
matrix=np.diag(np.arange(n,0,-1))
print(matrix)
print('сумма: {}'.format(sum(sum(matrix))))

5
[[5 0 0 0 0]
 [0 4 0 0 0]
 [0 0 3 0 0]
 [0 0 0 2 0]
 [0 0 0 0 1]]
сумма: 15


In [ ]:
# Задание 3
# Решите систему уравнений:
# 4x + 2y + z = 4
# x + 3y = 12
# 5y + 4z = -3

In [34]:
c = np.array([[4,2,1],[1,3,0],[0,5,4]])
d = np.array ([4,12,-3])

In [36]:
from numpy import linalg

In [38]:
linalg.solve(c,d)

array([ 0.46666667,  3.84444444, -5.55555556])

In [ ]:
#Задача 4 домашнего задания

In [42]:
#Матрица в виде numpy array

users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [49]:
# На сайт заходит очередной посетитель, о покупках которого известно следующее:

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [ ]:
#Найдите самого похожего пользователя. 
# Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [44]:
def cosine(users_stats, next_user_stats):
    # длины векторов
    users_stats_Length = np.linalg.norm(users_stats)
    next_user_stats_Length = np.linalg.norm(next_user_stats)
    
    return np.dot(users_stats, next_user_stats) / (users_stats_Length * next_user_stats_Length)

In [52]:
# результат вычислений
top = np.apply_along_axis(cosine, 1, users_stats, next_user_stats)
print(top)

[0.2        0.84515425 0.4        0.79056942 0.4        0.
 0.         0.9486833  0.         0.        ]


In [53]:
# наиболее подходящий
best_user = np.argmax(top)
print(best_user)

7
